Restyled by shfmt

diff --git a/tools/skema-kill b/tools/skema-kill
--- a/tools/skema-kill
+++ b/tools/skema-kill
@@ -19,20 +19,23 @@
 # Simple script to kill a 'skema' instance running a suite
 #
 
-declare -ar SKEMA_KILL_DEPS=( \
-    'ps' \
-    'grep' \
-    'awk' \
-    'kill' \
+declare -ar SKEMA_KILL_DEPS=(
+  'ps'
+  'grep'
+  'awk'
+  'kill'
 )
 
 # Check dependencies
 for cmd in "${SKEMA_KILL_DEPS[@]}"; do
-    command -v "$cmd" >/dev/null 2>&1 \
-        || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
+  command -v "$cmd" >/dev/null 2>&1 ||
+    {
+      echo >&2 "This program requires $cmd. Aborting."
+      exit 1
+    }
 done
 
 kill -TERM "$(ps aux | grep run_suite | grep python | awk '{ print $2 }')"
 if [[ $? -ne 0 ]]; then
-    kill -KILL "$(ps aux | grep run_suite | grep python | awk '{ print $2 }')"
+  kill -KILL "$(ps aux | grep run_suite | grep python | awk '{ print $2 }')"
 fi
diff --git a/tools/tizonia-dev-build-parallel b/tools/tizonia-dev-build-parallel
--- a/tools/tizonia-dev-build-parallel
+++ b/tools/tizonia-dev-build-parallel
@@ -24,64 +24,67 @@
 # NOTE: THIS IS WORK IN PROGRESS AND SHOULD NOT BE USED YET!!!!
 #
 
-declare -ar TIZONIA_DEV_BUILD_PARALLEL_DEPS=( \
-    'parallel' \
-    'tizonia-dev-build' \
+declare -ar TIZONIA_DEV_BUILD_PARALLEL_DEPS=(
+  'parallel'
+  'tizonia-dev-build'
 )
 
 source tizonia-common.inc
 
-function main {
-    # Check dependencies
-    for cmd in "${TIZONIA_DEV_BUILD_PARALLEL_DEPS[@]}"; do
-        command -v "$cmd" >/dev/null 2>&1 || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
-    done
+function main() {
+  # Check dependencies
+  for cmd in "${TIZONIA_DEV_BUILD_PARALLEL_DEPS[@]}"; do
+    command -v "$cmd" >/dev/null 2>&1 || {
+      echo >&2 "This program requires $cmd. Aborting."
+      exit 1
+    }
+  done
 
-    # Build include, gmusic, soundcloud, tunein, youtube, plex, and chromecast packages in parallel
-    local tmpsource="$(mktemp)"
-    for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
-        if [[ "${TIZ_PROJECT_DIRS[$proj]}" != *"proxy"* ]]; then
-            echo "Adding $proj"
-            echo "$proj" >> "$tmpsource"
-            if [[ "${TIZ_PROJECT_DIRS[$proj]}" == *"libtizplatform"* ]]; then
-                break
-            fi
-        fi
-    done
+  # Build include, gmusic, soundcloud, tunein, youtube, plex, and chromecast packages in parallel
+  local tmpsource="$(mktemp)"
+  for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
+    if [[ "${TIZ_PROJECT_DIRS[$proj]}" != *"proxy"* ]]; then
+      echo "Adding $proj"
+      echo "$proj" >>"$tmpsource"
+      if [[ "${TIZ_PROJECT_DIRS[$proj]}" == *"libtizplatform"* ]]; then
+        break
+      fi
+    fi
+  done
 
-    # Da business
-    cat "$tmpsource" | parallel --no-notice -k "tizonia-dev-build $@ --project"
+  # Da business
+  cat "$tmpsource" | parallel --no-notice -k "tizonia-dev-build $@ --project"
 
-    # Cleanup
-    rm "$tmpsource"
+  # Cleanup
+  rm "$tmpsource"
 
-    # Build platform, RM, core, and tizonia sequentially
-    for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
-        if [[ "${TIZ_PROJECT_DIRS[$proj]}" == *"plugins"* ]]; then
-            break
-        fi
-        if [[ ( "${TIZ_PROJECT_DIRS[$proj]}" != *"proxy"* ) || ( "${TIZ_PROJECT_DIRS[$proj]}" == "tizrmproxy" ) ]]; then
-            local proj_dir="$TIZONIA_REPO_DIR/${TIZ_PROJECT_DIRS[$proj]}"
-            pretty_print "$GRN" "[$proj] : $proj_dir"
-            tizonia-dev-build "$@" --project="$proj"
-        fi
-    done
+  # Build platform, RM, core, and tizonia sequentially
+  for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
+    if [[ "${TIZ_PROJECT_DIRS[$proj]}" == *"plugins"* ]]; then
+      break
+    fi
+    if [[ ("${TIZ_PROJECT_DIRS[$proj]}" != *"proxy"*) || ("${TIZ_PROJECT_DIRS[$proj]}" == "tizrmproxy") ]]; then
+      local proj_dir="$TIZONIA_REPO_DIR/${TIZ_PROJECT_DIRS[$proj]}"
+      pretty_print "$GRN" "[$proj] : $proj_dir"
+      tizonia-dev-build "$@" --project="$proj"
+    fi
+  done
 
-    # Build plugins, config and player in parallel
-    tmpsource=$(mktemp)
-    for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
-        if [[ "${TIZ_PROJECT_DIRS[$proj]}" == *"plugins"* \
-            || "${TIZ_PROJECT_DIRS[$proj]}" == *"config"* \
-            || "${TIZ_PROJECT_DIRS[$proj]}" == *"player"* ]]; then
-            echo "$proj" >> "$tmpsource"
-        fi
-    done
+  # Build plugins, config and player in parallel
+  tmpsource=$(mktemp)
+  for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
+    if [[ "${TIZ_PROJECT_DIRS[$proj]}" == *"plugins"* || \
+      "${TIZ_PROJECT_DIRS[$proj]}" == *"config"* || \
+      "${TIZ_PROJECT_DIRS[$proj]}" == *"player"* ]]; then
+      echo "$proj" >>"$tmpsource"
+    fi
+  done
 
-    # Da business
-    cat "$tmpsource" | parallel --no-notice -k "tizonia-dev-build $@ --project"
+  # Da business
+  cat "$tmpsource" | parallel --no-notice -k "tizonia-dev-build $@ --project"
 
-    # Cleanup
-    rm "$tmpsource"
+  # Cleanup
+  rm "$tmpsource"
 }
 
 main "$@"
diff --git a/tools/tizonia-smem b/tools/tizonia-smem
--- a/tools/tizonia-smem
+++ b/tools/tizonia-smem
@@ -19,15 +19,18 @@
 # Simple smem wrapper for the tizonia process
 #
 
-declare -ar TIZONIA_SMEM_DEPS=( \
-    'watch' \
-    'smem' \
+declare -ar TIZONIA_SMEM_DEPS=(
+  'watch'
+  'smem'
 )
 
 # Check dependencies
 for cmd in "${TIZONIA_SMEM_DEPS[@]}"; do
-    command -v "$cmd" >/dev/null 2>&1 \
-        || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
+  command -v "$cmd" >/dev/null 2>&1 ||
+    {
+      echo >&2 "This program requires $cmd. Aborting."
+      exit 1
+    }
 done
 
 watch -n60 'smem -p --processfilter="^tizonia "'
