Restyled by shfmt

diff --git a/tools/tizonia-coverity2github b/tools/tizonia-coverity2github
--- a/tools/tizonia-coverity2github
+++ b/tools/tizonia-coverity2github
@@ -23,8 +23,8 @@
 # The script uses gcli (github_cli)
 #
 
-declare -ar TIZONIA_COVERITY2GITHUB_DEPS=( \
-    'gcli' \
+declare -ar TIZONIA_COVERITY2GITHUB_DEPS=(
+  'gcli'
 )
 
 ##################################################################
@@ -37,31 +37,33 @@ declare -ar TIZONIA_COVERITY2GITHUB_DEPS=( \
 # Returns:
 #   None
 ##################################################################
-function main {
+function main() {
 
-    # Check dependencies
-    for cmd in "${TIZONIA_COVERITY2GITHUB_DEPS[@]}"; do
-        command -v "$cmd" >/dev/null 2>&1 \
-            || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
-    done
+  # Check dependencies
+  for cmd in "${TIZONIA_COVERITY2GITHUB_DEPS[@]}"; do
+    command -v "$cmd" >/dev/null 2>&1 ||
+      {
+        echo >&2 "This program requires $cmd. Aborting."
+        exit 1
+      }
+  done
 
-    while IFS=, read cid type impact status first_detected owner classification severity action component category file func
-    do
-        title="Coverity Scan (CID $cid) [$file:$func] : $type"
-        echo "Creating Githib issue : [$title]"
-        gcli issue create tizonia tizonia-openmax-il \
-            --title="Coverity Scan (CID $cid) [$file:$func] : $type" \
-            --labels=bug \
-            --body="* CID : $cid * Type : $type * Impact : $impact * Status : $status * First Detected : $first_detected * Classification : $classification * Severity : $severity * Component : $component * Category : $category * File : $file * Function : $func" \
-            --quiet
+  while IFS=, read cid type impact status first_detected owner classification severity action component category file func; do
+    title="Coverity Scan (CID $cid) [$file:$func] : $type"
+    echo "Creating Githib issue : [$title]"
+    gcli issue create tizonia tizonia-openmax-il \
+      --title="Coverity Scan (CID $cid) [$file:$func] : $type" \
+      --labels=bug \
+      --body="* CID : $cid * Type : $type * Impact : $impact * Status : $status * First Detected : $first_detected * Classification : $classification * Severity : $severity * Component : $component * Category : $category * File : $file * Function : $func" \
+      --quiet
 
-        if [[ $? -eq 0 ]]; then
-            echo "  Successfully created."
-        else
-            echo "  Something went wrong."
-        fi
+    if [[ $? -eq 0 ]]; then
+      echo "  Successfully created."
+    else
+      echo "  Something went wrong."
+    fi
 
-    done < coverity-scan-outstanding-defects.csv
+  done <coverity-scan-outstanding-defects.csv
 }
 
 main "$@"
diff --git a/tools/tizonia-htop b/tools/tizonia-htop
--- a/tools/tizonia-htop
+++ b/tools/tizonia-htop
@@ -19,18 +19,21 @@
 # Simple htop wrapper for the tizonia process
 #
 
-declare -ar TIZONIA_HTOP_DEPS=( \
-    'htop' \
-    'pstree' \
-    'pidof' \
-    'cut' \
-    'sed' \
+declare -ar TIZONIA_HTOP_DEPS=(
+  'htop'
+  'pstree'
+  'pidof'
+  'cut'
+  'sed'
 )
 
 # Check dependencies
 for cmd in "${TIZONIA_HTOP_DEPS[@]}"; do
-    command -v "$cmd" >/dev/null 2>&1 \
-        || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
+  command -v "$cmd" >/dev/null 2>&1 ||
+    {
+      echo >&2 "This program requires $cmd. Aborting."
+      exit 1
+    }
 done
 
 PROCNAME=tizonia
diff --git a/tools/tizonia-pidstat b/tools/tizonia-pidstat
--- a/tools/tizonia-pidstat
+++ b/tools/tizonia-pidstat
@@ -19,37 +19,40 @@
 # Simple pidstat wrapper for the tizonia process
 #
 
-declare -ar TIZONIA_PIDSTAT_DEPS=( \
-    'pidstat' \
-    'pidof' \
+declare -ar TIZONIA_PIDSTAT_DEPS=(
+  'pidstat'
+  'pidof'
 )
 
 PROCNAME=tizonia
 [[ -n "$2" ]] && { PROCNAME=$2; }
 
-function usagexit {
-    echo >&2 "$(basename "$0") [cpu|mem] [interval]"
-    exit 1
+function usagexit() {
+  echo >&2 "$(basename "$0") [cpu|mem] [interval]"
+  exit 1
 }
 
-function main {
+function main() {
 
-    # Check dependencies
-    for cmd in "${TIZONIA_PIDSTAT_DEPS[@]}"; do
-        command -v "$cmd" >/dev/null 2>&1 \
-            || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
-    done
+  # Check dependencies
+  for cmd in "${TIZONIA_PIDSTAT_DEPS[@]}"; do
+    command -v "$cmd" >/dev/null 2>&1 ||
+      {
+        echo >&2 "This program requires $cmd. Aborting."
+        exit 1
+      }
+  done
 
-    report=""
-    case "$1" in
-        cpu) report="-I";;
-        mem) report="-r";;
-        *) usagexit;;
-    esac
+  report=""
+  case "$1" in
+    cpu) report="-I" ;;
+    mem) report="-r" ;;
+    *) usagexit ;;
+  esac
 
-    interval=10
+  interval=10
 
-    pidstat "$interval" "$report" -p "$(pidof "$PROCNAME")"
+  pidstat "$interval" "$report" -p "$(pidof "$PROCNAME")"
 }
 
 main "$@"
diff --git a/tools/tizonia-prepare-release b/tools/tizonia-prepare-release
--- a/tools/tizonia-prepare-release
+++ b/tools/tizonia-prepare-release
@@ -48,9 +48,9 @@
 # 10.- Update CHANGELOG.md
 #     - using github-changelog-generator
 # 11.- Now Delete the tag in GitHub, push the changes to CHANGELOG.md and re-create the tag
-    # $ git tag -l
-    # $ git tag -d v0.2.0
-    # $ git push origin :refs/tags/v0.2.0
+# $ git tag -l
+# $ git tag -d v0.2.0
+# $ git push origin :refs/tags/v0.2.0
 # 12.- Build debian packages and upload to Bintray.
 # 13.- Update Tizonia's website.
 
@@ -58,11 +58,11 @@
 source tizonia-common.inc
 
 # Constants
-readonly TIZONIA_OLD_PACKAGE_VER="0.21.0"
+readonly TIZONIA_OLD_PACKAGE_VER="0.20.0"
 readonly TIZONIA_NEW_PACKAGE_VER="$TIZONIA_RELEASE_VERSION"
 
-readonly TIZONIA_OLD_SHLIB_VER="0:21:0"
-readonly TIZONIA_NEW_SHLIB_VER="0:22:0"
+readonly TIZONIA_OLD_SHLIB_VER="0:20:0"
+readonly TIZONIA_NEW_SHLIB_VER="0:21:0"
 
 readonly TIZONIA_PLUGIN_OLD_SHLIB_VER="$TIZONIA_OLD_SHLIB_VER"
 readonly TIZONIA_PLUGIN_NEW_SHLIB_VER="$TIZONIA_NEW_SHLIB_VER"
@@ -71,181 +71,182 @@ readonly TIZONIA_PYTHON_OLD_MODULE_VER="$TIZONIA_OLD_PACKAGE_VER"
 readonly TIZONIA_PYTHON_NEW_MODULE_VER="$TIZONIA_NEW_PACKAGE_VER"
 
 readonly TIZONIA_DEBIAN_CHANGELOG_VER="$TIZONIA_NEW_PACKAGE_VER"
-readonly TIZONIA_DEBIAN_CHANGELOG_CLOSING_BUG="735"
+readonly TIZONIA_DEBIAN_CHANGELOG_CLOSING_BUG="699"
 
 # Program dependencies
-declare -ar TIZONIA_PREPARE_RELEASE_DEPS=( \
-    'dch' \
-    'github_changelog_generator' \
-    'perl' \
-    'tail' \
-    'cut' \
-    'grcat' \
-    'tig' \
+declare -ar TIZONIA_PREPARE_RELEASE_DEPS=(
+  'dch'
+  'github_changelog_generator'
+  'perl'
+  'tail'
+  'cut'
+  'grcat'
+  'tig'
 )
 
+function update_package_versions() {
+  pretty_print "$MAG" "[START] : updating package versions."
+  cd "$TIZONIA_REPO_DIR"
+  local OLD_VER="$TIZONIA_OLD_PACKAGE_VER"
+  local NEW_VER="$TIZONIA_NEW_PACKAGE_VER"
+  local OLD_VER_QUOTED="$(echo "$OLD_VER" | sed -r 's/\./\\./g')"
+  perl -i -p -e "s/(?<=AC_INIT)(.*)\s\[$OLD_VER_QUOTED\]/\1 [$NEW_VER]/g" \
+    "$(find -L "$TIZONIA_REPO_DIR" -type f \( -path "./tools/*" -prune \) -o \( -name '*.ac' \) -print)"
+  pretty_print "$BLU" "[DONE] : updating package versions."
 
-function update_package_versions {
-    pretty_print "$MAG" "[START] : updating package versions."
-    cd "$TIZONIA_REPO_DIR"
-    local OLD_VER="$TIZONIA_OLD_PACKAGE_VER"
-    local NEW_VER="$TIZONIA_NEW_PACKAGE_VER"
-    local OLD_VER_QUOTED="$(echo "$OLD_VER" | sed -r 's/\./\\./g')"
-    perl -i -p -e "s/(?<=AC_INIT)(.*)\s\[$OLD_VER_QUOTED\]/\1 [$NEW_VER]/g" \
-        "$(find -L "$TIZONIA_REPO_DIR" -type f \( -path "./tools/*" -prune \) -o \( -name '*.ac' \) -print)"
-    pretty_print "$BLU" "[DONE] : updating package versions."
-
-    query_commit "update_package_versions"
+  query_commit "update_package_versions"
 }
 
-function update_shared_lib_versions {
-    pretty_print "$MAG" "[START] : updating shared lib versions."
-    cd "$TIZONIA_REPO_DIR"
-    local OLD_VER="$TIZONIA_OLD_SHLIB_VER"
-    local NEW_VER="$TIZONIA_NEW_SHLIB_VER"
-    perl -i -p -e "s/(?<=SHARED_VERSION_INFO=\")$OLD_VER/$NEW_VER/g" \
-        "$(find -L . -type f \( -path "./plugins/*" -prune \) -o \
-        \( -path "./tools/*" -prune \) -o \
-        \( -name '*.ac' \) -print)"
-    pretty_print "$BLU" "[DONE] : updating shared lib versions."
+function update_shared_lib_versions() {
+  pretty_print "$MAG" "[START] : updating shared lib versions."
+  cd "$TIZONIA_REPO_DIR"
+  local OLD_VER="$TIZONIA_OLD_SHLIB_VER"
+  local NEW_VER="$TIZONIA_NEW_SHLIB_VER"
+  perl -i -p -e "s/(?<=SHARED_VERSION_INFO=\")$OLD_VER/$NEW_VER/g" \
+    "$(find -L . -type f \( -path "./plugins/*" -prune \) -o \
+      \( -path "./tools/*" -prune \) -o \
+      \( -name '*.ac' \) -print)"
+  pretty_print "$BLU" "[DONE] : updating shared lib versions."
 
-    query_commit "update_shared_lib_versions"
+  query_commit "update_shared_lib_versions"
 }
 
-function update_plugin_shared_lib_versions {
-    pretty_print "$MAG" "[START] : updating plugins shared lib versions."
-    cd "$TIZONIA_REPO_DIR"/plugins
-    local OLD_VER="$TIZONIA_PLUGIN_OLD_SHLIB_VER"
-    local NEW_VER="$TIZONIA_PLUGIN_NEW_SHLIB_VER"
-    perl -i -p -e "s/(?<=SHARED_VERSION_INFO=\")$OLD_VER/$NEW_VER/g" \
-        "$(find -L . -type f \( -path "./tools/*" -prune \) -o \( -name '*.ac' \) -print)"
-    pretty_print "$BLU" "[DONE] : updating plugins shared lib versions."
+function update_plugin_shared_lib_versions() {
+  pretty_print "$MAG" "[START] : updating plugins shared lib versions."
+  cd "$TIZONIA_REPO_DIR"/plugins
+  local OLD_VER="$TIZONIA_PLUGIN_OLD_SHLIB_VER"
+  local NEW_VER="$TIZONIA_PLUGIN_NEW_SHLIB_VER"
+  perl -i -p -e "s/(?<=SHARED_VERSION_INFO=\")$OLD_VER/$NEW_VER/g" \
+    "$(find -L . -type f \( -path "./tools/*" -prune \) -o \( -name '*.ac' \) -print)"
+  pretty_print "$BLU" "[DONE] : updating plugins shared lib versions."
 
-    query_commit "update_plugin_shared_lib_versions"
+  query_commit "update_plugin_shared_lib_versions"
 }
 
-function update_python_version_strings {
-    pretty_print "$MAG" "[START] : updating python version strings."
-    cd "$TIZONIA_REPO_DIR"
-    local OLD_VER="$TIZONIA_PYTHON_OLD_MODULE_VER"
-    local NEW_VER="$TIZONIA_PYTHON_NEW_MODULE_VER"
-    perl -i -p -e "s/$OLD_VER/$NEW_VER/g" \
-        "$(find -L . -type f \( -path "./tools/*" -prune \) -o \( -name '_version.py' \) -print)"
-    pretty_print "$BLU" "[DONE] : updating python version strings."
+function update_python_version_strings() {
+  pretty_print "$MAG" "[START] : updating python version strings."
+  cd "$TIZONIA_REPO_DIR"
+  local OLD_VER="$TIZONIA_PYTHON_OLD_MODULE_VER"
+  local NEW_VER="$TIZONIA_PYTHON_NEW_MODULE_VER"
+  perl -i -p -e "s/$OLD_VER/$NEW_VER/g" \
+    "$(find -L . -type f \( -path "./tools/*" -prune \) -o \( -name '_version.py' \) -print)"
+  pretty_print "$BLU" "[DONE] : updating python version strings."
 
-    query_commit "update_python_version_strings"
+  query_commit "update_python_version_strings"
 }
 
-function update_debian_changelog_files {
-    pretty_print "$MAG" "[START] : updating Debian changelog files."
-    cd "$TIZONIA_REPO_DIR"
-    local NEW_VER="$TIZONIA_DEBIAN_CHANGELOG_VER"
-    local CLOSING_BUG="$TIZONIA_DEBIAN_CHANGELOG_CLOSING_BUG"
-    for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
-        local proj_dir="$TIZONIA_REPO_DIR/${TIZ_PROJECT_DIRS[$proj]}"
-        cd "$proj_dir"
-        dch --newversion "$NEW_VER"-1 --upstream --urgency low --distribution unstable "New upstream release (Closes: #$CLOSING_BUG)"
-    done
-    pretty_print "$BLU" "[DONE] : updating Debian changelog files."
+function update_debian_changelog_files() {
+  pretty_print "$MAG" "[START] : updating Debian changelog files."
+  cd "$TIZONIA_REPO_DIR"
+  local NEW_VER="$TIZONIA_DEBIAN_CHANGELOG_VER"
+  local CLOSING_BUG="$TIZONIA_DEBIAN_CHANGELOG_CLOSING_BUG"
+  for proj in "${TIZ_PROJECTS_ORDERED[@]}"; do
+    local proj_dir="$TIZONIA_REPO_DIR/${TIZ_PROJECT_DIRS[$proj]}"
+    cd "$proj_dir"
+    dch --newversion "$NEW_VER"-1 --upstream --urgency low --distribution unstable "New upstream release (Closes: #$CLOSING_BUG)"
+  done
+  pretty_print "$BLU" "[DONE] : updating Debian changelog files."
 
-    query_commit "update_debian_changelog_files"
+  query_commit "update_debian_changelog_files"
 }
 
-function update_doxygen_doc_version_strings {
-    pretty_print "$MAG" "[START] : updating Doxygen doc versions."
-    cd "$TIZONIA_REPO_DIR"/docs
-    local OLD_VER="$TIZONIA_OLD_PACKAGE_VER"
-    local NEW_VER="$TIZONIA_NEW_PACKAGE_VER"
-    perl -i -p -e "s/$OLD_VER/$NEW_VER/g" \
-        "$(find -L "$TIZONIA_REPO_DIR" -type f -name 'doxyfile.rtd' -print)"
-    pretty_print "$BLU" "[DONE] : updating Doxygen doc versions."
+function update_doxygen_doc_version_strings() {
+  pretty_print "$MAG" "[START] : updating Doxygen doc versions."
+  cd "$TIZONIA_REPO_DIR"/docs
+  local OLD_VER="$TIZONIA_OLD_PACKAGE_VER"
+  local NEW_VER="$TIZONIA_NEW_PACKAGE_VER"
+  perl -i -p -e "s/$OLD_VER/$NEW_VER/g" \
+    "$(find -L "$TIZONIA_REPO_DIR" -type f -name 'doxyfile.rtd' -print)"
+  pretty_print "$BLU" "[DONE] : updating Doxygen doc versions."
 
-    query_commit "update_doxygen_doc_version_strings"
+  query_commit "update_doxygen_doc_version_strings"
 }
 
-function update_sphinx_doc_version_strings {
-    pretty_print "$MAG" "[START] : updating Sphinx doc versions."
-    cd "$TIZONIA_REPO_DIR"/docs
-    local OLD_VER="$TIZONIA_OLD_PACKAGE_VER"
-    local NEW_VER="$TIZONIA_NEW_PACKAGE_VER"
-    perl -i -p -e "s/$OLD_VER/$NEW_VER/g" \
-        "$(find -L "$TIZONIA_REPO_DIR" -type f -name 'conf.py' -print)"
-    pretty_print "$BLU" "[DONE] : updating Sphinx doc versions."
+function update_sphinx_doc_version_strings() {
+  pretty_print "$MAG" "[START] : updating Sphinx doc versions."
+  cd "$TIZONIA_REPO_DIR"/docs
+  local OLD_VER="$TIZONIA_OLD_PACKAGE_VER"
+  local NEW_VER="$TIZONIA_NEW_PACKAGE_VER"
+  perl -i -p -e "s/$OLD_VER/$NEW_VER/g" \
+    "$(find -L "$TIZONIA_REPO_DIR" -type f -name 'conf.py' -print)"
+  pretty_print "$BLU" "[DONE] : updating Sphinx doc versions."
 
-    query_commit "update_sphinx_doc_version_strings"
+  query_commit "update_sphinx_doc_version_strings"
 }
 
-function update_man_page {
-    pretty_print "$MAG" "[START] : updating Tizonia man page."
-    cd "$TIZONIA_REPO_DIR"/docs
-    autoreconf -ifs && ./configure && make
-    cd "$TIZONIA_REPO_DIR"/docs/sphinx-src
-    make man
-    cp _build/man/tizonia.1 "$TIZONIA_REPO_DIR"/player/man/tizonia.1
-    pretty_print "$BLU" "[DONE] : updating Tizonia man page."
+function update_man_page() {
+  pretty_print "$MAG" "[START] : updating Tizonia man page."
+  cd "$TIZONIA_REPO_DIR"/docs
+  autoreconf -ifs && ./configure && make
+  cd "$TIZONIA_REPO_DIR"/docs/sphinx-src
+  make man
+  cp _build/man/tizonia.1 "$TIZONIA_REPO_DIR"/player/man/tizonia.1
+  pretty_print "$BLU" "[DONE] : updating Tizonia man page."
 
-    query_commit "update_man_page"
+  query_commit "update_man_page"
 }
 
-function update_changelog {
-    cd "$TIZONIA_REPO_DIR"
-    github_changelog_generator --since-tag v0.1.0 --user=tizonia --project=tizonia-openmax-il --future-release "$TIZONIA_RELEASE_VERSION" --enhancement-label "**Improvements:**"
+function update_changelog() {
+  cd "$TIZONIA_REPO_DIR"
+  github_changelog_generator --since-tag v0.1.0 --user=tizonia --project=tizonia-openmax-il --future-release "$TIZONIA_RELEASE_VERSION" --enhancement-label "**Improvements:**"
 
-    query_commit "update_changelog"
+  query_commit "update_changelog"
 }
 
-function query_commit {
-    tig
-    echo
-    read -p "Commmit? " -n 1 -r
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
-        git reset -- "$TIZONIA_REPO_DIR"/tools/tizonia-prepare-release
-        git commit -a --message="release $TIZONIA_RELEASE_VERSION: $1 (#$TIZONIA_DEBIAN_CHANGELOG_CLOSING_BUG)"
-    else
-        git-clear
-    fi
-    echo
-    read -p "Continue? " -n 1 -r && [[ $REPLY =~ ^[Yy]$ ]] || exit 1
-    echo
+function query_commit() {
+  tig
+  echo
+  read -p "Commmit? " -n 1 -r
+  if [[ $REPLY =~ ^[Yy]$ ]]; then
+    git reset -- "$TIZONIA_REPO_DIR"/tools/tizonia-prepare-release
+    git commit -a --message="release $TIZONIA_RELEASE_VERSION: $1 (#$TIZONIA_DEBIAN_CHANGELOG_CLOSING_BUG)"
+  else
+    git-clear
+  fi
+  echo
+  read -p "Continue? " -n 1 -r && [[ $REPLY =~ ^[Yy]$ ]] || exit 1
+  echo
 }
 
-function main {
-    [[ "$TIZONIA_OLD_PACKAGE_VER" != "$TIZONIA_NEW_PACKAGE_VER" ]] || { echo >&2 "Forgot to update TIZONIA_RELEASE_VERSION. Aborting."; exit 1; }
+function main() {
+  [[ "$TIZONIA_OLD_PACKAGE_VER" != "$TIZONIA_NEW_PACKAGE_VER" ]] || {
+    echo >&2 "Forgot to update TIZONIA_RELEASE_VERSION. Aborting."
+    exit 1
+  }
 
-    # Check dependencies
-    for cmd in "${TIZONIA_PREPARE_RELEASE_DEPS[@]}"; do
-        command -v "$cmd" >/dev/null 2>&1 \
-            || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
-    done
+  # Check dependencies
+  for cmd in "${TIZONIA_PREPARE_RELEASE_DEPS[@]}"; do
+    command -v "$cmd" >/dev/null 2>&1 ||
+      {
+        echo >&2 "This program requires $cmd. Aborting."
+        exit 1
+      }
+  done
 
-    print_banner "[START] : Preparing Tizonia for release; version [$TIZONIA_RELEASE_VERSION]" "$YEL"
+  print_banner "[START] : Preparing Tizonia for release; version [$TIZONIA_RELEASE_VERSION]" "$YEL"
 
-    # These steps below are automated. Uncomment all of them. Run this script
-    # to do all this in one go.
+  # update_package_versions
+  # update_plugin_shared_lib_versions
+  # update_shared_lib_versions
+  # update_python_version_strings
+  # update_debian_changelog_files
+  # update_doxygen_doc_version_strings
+  # update_sphinx_doc_version_strings
+  # update_man_page
 
-    # update_package_versions
-    # update_plugin_shared_lib_versions
-    # update_shared_lib_versions
-    # update_python_version_strings
-    # update_debian_changelog_files
-    # update_doxygen_doc_version_strings
-    # update_sphinx_doc_version_strings
-    # update_man_page
+  # Do the following manual steps at this point
+  # 7.- Update README.md (as many changes as needed).
+  # 8.- Close github issue: release vx.x.x
+  # 9.- Create release and tag it on GitHub.
 
-    # Do the following manual steps at this point
+  # update_changelog
 
-    # 7.- Update README.md (as many changes as needed).
-    # 8.- Close github issue: release vx.x.x
-    # 9.- Create release and tag it on GitHub.
+  # Now Delete the tag on Github, push the changes to CHANGELOG.md and re-create the tag
+  # $ git tag -l
+  # $ git tag -d v0.2.0
+  # $ git push origin :refs/tags/v0.2.0
 
-    # update_changelog
-
-    # Now Delete the tag on Github, push the changes to CHANGELOG.md and re-create the tag
-    # $ git tag -l
-    # $ git tag -d v0.2.0
-    # $ git push origin :refs/tags/v0.2.0
-
-    print_banner "[DONE] : Updating files." "$BLU"
+  print_banner "[DONE] : Updating files." "$BLU"
 
 }
 
diff --git a/tools/tizonia-tail b/tools/tizonia-tail
--- a/tools/tizonia-tail
+++ b/tools/tizonia-tail
@@ -21,16 +21,19 @@
 TIZONIA_GRCAT_CONFIG="$TIZONIA_REPO_DIR"/tools/tizonia.grcat.conf
 TIZONIA_LOG_FILE="$HOME"/temp/tizonia.log.0
 
-declare -ar TIZONIA_TAIL_DEPS=( \
-    'tail' \
-    'cut' \
-    'grcat' \
+declare -ar TIZONIA_TAIL_DEPS=(
+  'tail'
+  'cut'
+  'grcat'
 )
 
 # Check dependencies
 for cmd in "${TIZONIA_TAIL_DEPS[@]}"; do
-    command -v "$cmd" >/dev/null 2>&1 \
-        || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
+  command -v "$cmd" >/dev/null 2>&1 ||
+    {
+      echo >&2 "This program requires $cmd. Aborting."
+      exit 1
+    }
 done
 
 tail -F "$TIZONIA_LOG_FILE" | awk '{for (i=5; i<NF; i++) printf $i " "; print $NF}' | grcat "$TIZONIA_GRCAT_CONFIG"
diff --git a/tools/tizonia-text-substitution-helper b/tools/tizonia-text-substitution-helper
--- a/tools/tizonia-text-substitution-helper
+++ b/tools/tizonia-text-substitution-helper
@@ -26,35 +26,38 @@ source tizonia-common.inc
 # Constants
 
 # Program dependencies
-declare -ar TIZONIA_PREPARE_RELEASE_DEPS=( \
-    'perl' \
-    'tail' \
-    'cut' \
+declare -ar TIZONIA_PREPARE_RELEASE_DEPS=(
+  'perl'
+  'tail'
+  'cut'
 )
 
-function update_configure_ac_files {
-    pretty_print "$MAG" "[START] : updating configure.ac files."
-    cd "$TIZONIA_REPO_DIR"/plugins/file_reader
-    local NEW_TEXT="$(printf "# Define location of plugin directory\nAS_AC_EXPAND(PLUGINDIR, \${libdir}\/tizonia0-plugins12)\nAC_DEFINE_UNQUOTED(PLUGINDIR, \"\$PLUGINDIR\",\n  [Directory where Tizonia plugins are located])\nAC_MSG_NOTICE([Using \$PLUGINDIR as the components install location])\n# Define plugin directory configure-time variable\nAC_SUBST([plugindir], ['\${libdir}\/tizonia0-plugins12'])\n\n# Checks for header files")"
-    echo "$NEW_TEXT"
-    perl -i -p -e "s/\#\sChecks\sfor\sheader\sfiles/$NEW_TEXT/g" \
-        "$(find "$TIZONIA_REPO_DIR"/plugins -type f \( -path "./tools/*" -prune \) -o \( -name '*.ac' \) -print)"
-    pretty_print "$BLU" "[DONE] : updating configure.ac files."
+function update_configure_ac_files() {
+  pretty_print "$MAG" "[START] : updating configure.ac files."
+  cd "$TIZONIA_REPO_DIR"/plugins/file_reader
+  local NEW_TEXT="$(printf "# Define location of plugin directory\nAS_AC_EXPAND(PLUGINDIR, \${libdir}\/tizonia0-plugins12)\nAC_DEFINE_UNQUOTED(PLUGINDIR, \"\$PLUGINDIR\",\n  [Directory where Tizonia plugins are located])\nAC_MSG_NOTICE([Using \$PLUGINDIR as the components install location])\n# Define plugin directory configure-time variable\nAC_SUBST([plugindir], ['\${libdir}\/tizonia0-plugins12'])\n\n# Checks for header files")"
+  echo "$NEW_TEXT"
+  perl -i -p -e "s/\#\sChecks\sfor\sheader\sfiles/$NEW_TEXT/g" \
+    "$(find "$TIZONIA_REPO_DIR"/plugins -type f \( -path "./tools/*" -prune \) -o \( -name '*.ac' \) -print)"
+  pretty_print "$BLU" "[DONE] : updating configure.ac files."
 }
 
-function main {
+function main() {
 
-    # Check dependencies
-    for cmd in "${TIZONIA_PREPARE_RELEASE_DEPS[@]}"; do
-        command -v "$cmd" >/dev/null 2>&1 \
-            || { echo >&2 "This program requires $cmd. Aborting."; exit 1; }
-    done
+  # Check dependencies
+  for cmd in "${TIZONIA_PREPARE_RELEASE_DEPS[@]}"; do
+    command -v "$cmd" >/dev/null 2>&1 ||
+      {
+        echo >&2 "This program requires $cmd. Aborting."
+        exit 1
+      }
+  done
 
-    print_banner "[START] : Updating files." "$YEL"
+  print_banner "[START] : Updating files." "$YEL"
 
-    update_configure_ac_files
+  update_configure_ac_files
 
-    print_banner "[DONE] : Updating files." "$BLU"
+  print_banner "[DONE] : Updating files." "$BLU"
 
 }
 
