Fix copy_config_files function

diff --git a/tools/tizonia-travis-build-bionic b/tools/tizonia-travis-build-bionic
--- a/tools/tizonia-travis-build-bionic
+++ b/tools/tizonia-travis-build-bionic
@@ -1,44 +1,41 @@
 #!/bin/bash
+# Tizonia's TravisCI build script for Ubuntu 18.04.06 LTS "Bionic" images
+# SPDX-License-Identifier: GPL-3.0-or-later
 #
 # Copyright (C) 2011-2020 Aratelia Limited - Juan A. Rubio and contributors
 #
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
+# This program is free software: you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation, either version 3 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 #
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-#
-# Tizonia's Travis-ci build script - for Travis' Ubuntu 14.04 image
-#
+# You should have received a copy of the GNU General Public License along with
+# this program. If not, see <https://www.gnu.org/licenses/>.
 
 # Globals
-WORKING_DIR="$HOME/tizonia-openmax-il" # Default value for working directory
-INSTALL_DIR="$HOME/build"              # Default value for install directory
-TIZRMD_PID=-1
+typeset -gx WORKING_DIR="${HOME}/tizonia-openmax-il" # Default value for working directory
+typeset -gx INSTALL_DIR="${HOME}/build"              # Default value for install directory
 
 # Constants
-readonly E_BADARGS=85
-readonly E_NOFILE=86
-readonly E_BAD_CLONE=87
+typeset -grx E_BADARGS=85
+typeset -grx E_NOFILE=86
+typeset -grx E_BAD_CLONE=87
 
-readonly TIZONIA_CONF_PATH="$HOME/.config/tizonia/tizonia.conf"
+typeset -grx TIZONIA_CONF_PATH="${HOME}/.config/tizonia/tizonia.conf"
 
-readonly SKEMA_GIT_REPO=https://github.com/tizonia/skema
-readonly SKEMA_DIR="$INSTALL_DIR"/skema
-readonly SKEMA_BIN_DIR="$SKEMA_DIR"/bin
+typeset -grx SKEMA_GIT_REPO="https://github.com/tizonia/skema.git"
+typeset -grx SKEMA_DIR="$INSTALL_DIR"/skema
+typeset -grx SKEMA_BIN_DIR="$SKEMA_DIR"/bin
 
+TIZRMD_PID=-1
 readonly MAXJOBS=12
 readonly CORES="$(grep -c ^processor /proc/cpuinfo)"
 readonly CORESMINUSONE=$((CORES - 1))
-readonly JOBS=$(($CORESMINUSONE < $MAXJOBS ? $CORESMINUSONE : $MAXJOBS))
+readonly JOBS=$((CORESMINUSONE < MAXJOBS ? CORESMINUSONE : MAXJOBS))
 
 # A list of skema test suites that should NOT be executed (i.e are disabled)
 declare -ar SKEMA_EXEMPT_SUITES=(
@@ -64,11 +61,12 @@ declare -ar SKEMA_NON_QUIET_SUITES=(
 LIB_DIR="$INSTALL_DIR"/lib
 BIN_DIR="$INSTALL_DIR"/bin
 PKG_CONFIG_DIR="$LIB_DIR"/pkgconfig
+PY3_USER_SITE_DIR="$(python3 -m site --user-site)"
 export PKG_CONFIG_PATH="$PKG_CONFIG_DIR"
 export LD_LIBRARY_PATH="$LIB_DIR"
 export PATH="$BIN_DIR:$PATH"
 # Export $PYTHONPATH to make sure soundcloud and gmusicapi can be found
-export PYTHONPATH="$PYTHONPATH":"$HOME"/.local/lib/python3.6/site-packages
+export PYTHONPATH="${PYTHONPATH}:${PY3_USER_SITE_DIR}"
 
 ##################################################################
 # Simple function to print a debug/error message with some extra info
@@ -81,7 +79,7 @@ export PYTHONPATH="$PYTHONPATH":"$HOME"/.local/lib/python3.6/site-packages
 #   None
 ##################################################################
 function err() {
-  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
 }
 
 ##################################################################
@@ -96,7 +94,7 @@ function err() {
 ##################################################################
 function cd_to_working_dir() {
   echo "Changing dir to working directory: $WORKING_DIR"
-  cd "$WORKING_DIR"
+  cd "$WORKING_DIR" || exit 1
 }
 
 ##################################################################
@@ -128,7 +126,8 @@ function exists_in_array() {
 ##################################################################
 function start_dbus() {
   # Only start D-BUS and the RM daemon if RM is enabled in tizonia.conf
-  local rm_needed="$(sed -rn 's/^enabled(\s*)=(\s*)(true|false)/\3/p' "$TIZONIA_CONF_PATH")"
+  rm_needed="$(sed -rn 's/^enabled(\s*)=(\s*)(true|false)/\3/p' "$TIZONIA_CONF_PATH")"
+  typeset rm_needed
   if [[ "$rm_needed" == "true" ]]; then
     ## test for an existing bus daemon, just to be safe
     if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
@@ -144,7 +143,7 @@ function start_dbus() {
       err "Unable to start the resource manager deamon"
       exit 1
     fi
-    echo "Tizonia RM daemon instantiated: pid $ltrmdpid."
+    echo "Tizonia RM daemon instantiated: pid $TIZRMD_PID."
   fi
 }
 
@@ -159,72 +158,57 @@ function start_dbus() {
 #   0 on success
 ##################################################################
 function install_deps() {
+  echo "Adding Mopidy apt repository for libspotify12..."
+  wget -qO- http://apt.mopidy.com/mopidy.gpg | sudo apt-key add - &&
+    echo -e "\\ndeb http://apt.mopidy.com/ stretch main contrib non-free
+    \\ndeb-src http://apt.mopidy.com/ stretch main contrib non-free" |
+    sudo tee -a /etc/apt/sources.list
   echo "Installing Tizonia's dependencies..."
-  sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y &&
-    sudo apt-get install -y \
-      apt-transport-https \
-      build-essential \
-      autoconf \
-      autoconf-archive \
-      automake \
-      autotools-dev \
-      bash-completion \
-      libtool \
-      libmad0-dev \
-      liblog4c-dev \
-      libasound2-dev \
-      libdbus-1-dev \
-      libsqlite3-dev \
-      libboost-all-dev \
-      uuid-dev \
-      libsdl1.2-dev \
-      libvpx-dev \
-      libmp3lame-dev \
-      libfaad-dev \
-      libtag1-dev \
-      libfishsound1-dev \
-      libmediainfo-dev \
-      libcurl4-gnutls-dev \
-      libpulse-dev \
-      libmpg123-dev \
-      libvorbis-dev \
-      libopus-dev \
-      libopusfile-dev \
-      libogg-dev \
-      libflac-dev \
-      liboggz2-dev \
-      libsndfile1-dev \
-      libffi-dev \
-      libssl-dev \
-      libmp4v2-dev \
-      libexpat1-dev \
-      libev-dev \
-      python3-dev \
-      python3-all-dev \
-      python3-setuptools \
-      python3-pip \
-      curl \
-      check \
-      wget \
-      sqlite3 \
-      dbus-x11 \
-      mercurial \
-      lcov
+  typeset -gx APTYES='sudo DEBIAN_FRONTEND=noninteractive apt -y'
+  "${APTYES}" update; "${APTYES}" upgrade; "${APTYES}" full-upgrade
+  "${APTYES}" install apt-transport-https \
+                      autoconf-archive \
+                      automake \
+                      bash-completion \
+                      build-essential \
+                      check \
+                      curl \
+                      dbus-x11 \
+                      lcov \
+                      libboost-all-dev \
+                      libdbus-1-dev \
+                      libev-dev \
+                      libexpat1-dev \
+                      libfaad-dev \
+                      libffi-dev \
+                      libfishsound1-dev \
+                      liblog4c-dev \
+                      libmad0-dev \
+                      libmediainfo-dev \
+                      libmp3lame-dev \
+                      libmp4v2-dev \
+                      libmpg123-dev \
+                      liboggz2-dev \
+                      libopusfile-dev \
+                      libsdl1.2-dev \
+                      libsndfile1-dev \
+                      libspotify-dev \
+                      libsqlite3-dev \
+                      libssl-dev \
+                      libtag1-dev \
+                      libtool \
+                      libvpx-dev \
+                      mercurial \
+                      python3-all-dev \
+                      python3-pip \
+                      sqlite3 \
+                      uuid-dev \
+                      wget
 
   exit_status=$?
 
   if [[ "$exit_status" -ne 0 ]]; then
     echo "Error while installing debian dependencies" >&2
-  fi
-
-  if [[ "$exit_status" -eq 0 ]]; then
-    echo "Installing libspotify..."
-    wget -q -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
-    echo deb http://apt.mopidy.com/ stretch main contrib non-free | sudo tee -a /etc/apt/sources.list
-    echo deb-src http://apt.mopidy.com/ stretch main contrib non-free | sudo tee -a /etc/apt/sources.list
-    sudo apt-get update -qq &&
-      sudo apt-get install libspotify12 libspotify-dev -qq
-    exit_status=$?
   fi
 
   return "$exit_status"
@@ -351,13 +335,13 @@ function install_python_deps() {
     fi
   fi
 
-  echo "Finding out about the default python installation"
-  which python
-  which python3
-  echo "PYTHONPATH=$PYTHONPATH"
-  echo "PYTHON_VERSION=$PYTHON_VERSION"
-  ls -l /usr/bin/python*
-  ls -l ~/.local/lib/
+  echo -e "Finding out about the default python installation...
+  python: $(command -v python)
+  python3: $(command -v python3)
+  PYTHONPATH: $(printenv PYTHONPATH)
+  PYTHON_VERSION: $(printenv PYTHON_VERSION)
+  ls -l /usr/bin/python*:\\n\\t$(ls -l /usr/bin/python*)
+  ls -l ~/.local/lib:\\n\\t$(ls -l ~/.local/lib)"
 
   return "$exit_status"
 }
@@ -376,24 +360,19 @@ function copy_config_files() {
   cd_to_working_dir
   echo "Copy the Resource Manager's D-bus service file " \
     "to the user's local D-Bus search path"
-  echo "$INSTALL_DIR"
-  local DBUS_SERVICE_FILE="$INSTALL_DIR/share/dbus-1/services/com.aratelia.tiz.rm.service"
+  echo "INSTALL_DIR: ${INSTALL_DIR}"; echo "Config file: ${TIZONIA_CONF_PATH}"
   local DBUS_DIR="$HOME/.local/share/dbus-1/services"
-  mkdir -p "$DBUS_DIR" && cp "$DBUS_SERVICE_FILE" "$DBUS_DIR"
+  mkdir -pv "${DBUS_DIR}" "${HOME}/.config/tizonia"
+  echo -e "[D-BUS Service]\\nName=com.aratelia.tiz.tizrmd\\nExec=${INSTALL_DIR}/bin/tizrmd" |
+    tee --output-error=warn "${DBUS_DIR}"/com.aratelia.tiz.rm.service
   local exit_status=$?
   if [[ "$exit_status" -eq 0 ]]; then
     echo "Preparing the $TIZONIA_CONF_PATH config file..."
-    mkdir -p "$HOME/.config/tizonia" &&
-      cp "$WORKING_DIR/config/src/tizonia.conf" "$TIZONIA_CONF_PATH"
+    cp -fv "${INSTALL_DIR}/etc/xdg/tizonia/tizonia.conf" "$(dirname "${TIZONIA_CONF_PATH}")"
+    perl -pi -e 's/^(OMX\..*alsa_device.*)\bdefault\b/\1null/' "${TIZONIA_CONF_PATH}"
     exit_status=$?
   fi
 
-  # Modify tizonia config to make the ALSA renderer use the null pcm
-  if [[ "$exit_status" -eq 0 ]]; then
-    echo "Preparing the $TIZONIA_CONF_PATH config file..."
-    perl -pi -e 's/^(OMX\..*alsa_device.*)\bdefault\b/\1null/' "$TIZONIA_CONF_PATH"
-    exit_status=$?
-  fi
   return "$exit_status"
 }
 
@@ -496,11 +475,11 @@ function install_skema() {
   fi
 
   # Step #2: Install skema's tags
-  cd "$SKEMA_BIN_DIR"
+  cd "$SKEMA_BIN_DIR" || return 1
 
   local tags=("$(./skema list_tags)")
   local tag_count="${#tags[@]}"
-  echo "Installing all $tag_count tags..."
+  echo "Installing $tag_count tag(s)..."
   for t in "${tags[@]}"; do
     echo "Installing [$t]"
     ./skema uninstall_tag "$t"
@@ -511,7 +490,7 @@ function install_skema() {
   local installed_tags=("$(./skema list_installed_tags)")
   local installed_tag_count="${#installed_tags[@]}"
   if [[ "$installed_tag_count" -ne "$tag_count" ]]; then
-    err "Error while installing tags"
+    err "Error while installing tag(s)"
     exit 1
   fi
 
@@ -519,7 +498,7 @@ function install_skema() {
   echo
   local suites=("$(./skema list_suites)")
   local suite_count="${#suites[@]}"
-  echo "Installing all $suite_count suites..."
+  echo "Installing $suite_count suite(s)..."
   for s in "${suites[@]}"; do
     echo "Installing [$s]"
     ./skema uninstall_suite "$s"
@@ -530,7 +509,7 @@ function install_skema() {
   local installed_suites=("$(./skema list_installed_suites)")
   local installed_suite_count="${#installed_suites[@]}"
   if [[ "$installed_suite_count" -ne "$suite_count" ]]; then
-    err "Error while installing suites"
+    err "Error while installing suite(s)"
     exit 1
   fi
   return "$exit_status"
@@ -553,7 +532,7 @@ function run_suites() {
   # D-Bus has been already started
   # start_dbus
 
-  cd "$SKEMA_BIN_DIR"
+  cd "$SKEMA_BIN_DIR" || return 1
 
   # Retrieve the list of installed suites
   local installed_suites=("$(./skema list_installed_suites)")
@@ -621,51 +600,59 @@ function run_coverage() {
 ##################################################################
 function main() {
 
-  if [[ "$2" != "" ]]; then
-    WORKING_DIR="$2"
-  fi
-
-  if [[ "$3" != "" ]]; then
-    INSTALL_DIR="$3"
+  if [[ "$#" -ge 2 ]]; then
+    typeset -grx WORKING_DIR="${2}"
+    if [[ "$#" -ge 3 ]]; then
+      typeset -grx INSTALL_DIR="${3}"
+    fi
   fi
 
   # Create directories
   if [[ ! -d "$INSTALL_DIR" ]]; then
-    echo "Creating the install directory: $INSTALL_DIR"
-    mkdir -p "$INSTALL_DIR"
+    echo "Creating the install directory..."
+    mkdir -pv "$INSTALL_DIR"
   fi
 
   echo "Changing dir to working directory: $WORKING_DIR"
-  cd "$WORKING_DIR"
+  cd "$WORKING_DIR" || return 1
 
-  if [[ "$1" == "deps" ]]; then
-    install_deps
-  elif [[ "$1" == "pydeps" ]]; then
-    install_python_deps
-  elif [[ "$1" == "build" ]]; then
-    configure_and_build
-  elif [[ "$1" == "media" ]]; then
-    cd_to_working_dir
-    echo "Downloading test media files to $INSTALL_DIR..."
-    mkdir -p "$INSTALL_DIR" &&
-      cd "$INSTALL_DIR" &&
+  case "${1}" in
+    deps)
+      install_deps
+      ;;
+    pydeps)
+      install_python_deps
+      ;;
+    build)
+      configure_and_build
+      ;;
+    media)
+      cd_to_working_dir
+      echo "Downloading test media files to $INSTALL_DIR..."
+      mkdir -pv "$INSTALL_DIR" && cd "$INSTALL_DIR" || return 1
       wget http://www.aratelia.com/tizonia/tizonia-test-media.tgz &&
       tar zxvf tizonia-test-media.tgz &>/dev/null
-  elif [[ "$1" == "config" ]]; then
-    copy_config_files
-  elif [[ "$1" == "unit" ]]; then
-    run_unit
-  elif [[ "$1" == "skema" ]]; then
-    install_skema
-  elif [[ "$1" == "suites" ]]; then
-    run_suites
-  elif [[ "$1" == "coverage" ]]; then
-    run_coverage
-  else
-    CMD=$(basename "$0")
-    echo "Usage: $CMD <deps|pydeps|media|build|config|skema|tests|coverage> <working_dir> <install_dir>"
-    exit 1
-  fi
+      ;;
+    config)
+      copy_config_files
+      ;;
+    unit)
+      run_unit
+      ;;
+    skema)
+      install_skema
+      ;;
+    suites)
+      run_suites
+      ;;
+    coverage)
+      run_coverage
+      ;;
+    *)
+      CMD=$(basename "${0}")
+      echo "Usage: $CMD <deps|pydeps|media|build|config|skema|tests|coverage> [build dir] [install dir]"
+      exit 1
+  esac
 
   exit $?
 }
